#arch: amd64
virt: lxd
#os: linux
#dist: focal
#sudo: false

language: go
#services:
#  - docker
install:
  - pip install --user awscli

jobs:
  include:
    - stage: test
      name: Run Go tests
      script:
        - go test -count 1 -race ./...
    - stage: test
      name: Check for AWS CLI availability
      script:
        - aws --version
    - stage: test
      name: Check for Docker
      script:
        - docker ps
        - docker run --rm -it hello-world
